### PR TITLE
Fix go.{mod,sum}

### PR DESCRIPTION
**Pull request by subham-deepsource**
Hello 👋 

I'm from the DeepSource team and we noticed that our Go analyzer was failing for your repository because during loading of packages:
```
../../../../pkg/mod/github.com/yudai/gotty@v2.0.0-alpha.3+incompatible/utils/flags.go:10:2: no required module provides package github.com/codegangsta/cli; to add it:
	go get github.com/codegangsta/cli
```

And if do the recommended:
```
go get github.com/codegangsta/cli
go get: github.com/codegangsta/cli@v1.20.0 updating to
	github.com/codegangsta/cli@v1.22.5: parsing go.mod:
	module declares its path as: github.com/urfave/cli
	        but was required as: github.com/codegangsta/cli
```

As the `go.mod` declares `github.com/urfave/cli` as the module path instead of `github.com/codegangsta/cli`, we could use the `replace` directive. Similar to: https://github.com/9elements/go-ser2net/blob/master/go.mod

At DeepSource, we load packages to provide contextual analysis by using rules that require types info and SSA IR. Hence, we require the modules to be set property i.e., `go.{mod,sum}` should be correct.

This PR should fix the problem described above. Let us know if you have any queries.

Signed-off-by: subham sarkar <subham@deepsource.io>

### CODE REVIEW

**Comment by subham-deepsource** [comment]
Because of merging multiple PRs involving `go.{mod,sum}`, you need to update it again. Could you please run `go mod tidy`? Then it'd be perfect; although it's still running but it's just recommended.

**Comment by johnsonjh** [comment]
Thanks for the update - I've tidied up the module dependencies.

**Comment by johnsonjh** [comment]
@subham-deepsource 

I appreciate you looking into this - I don't always rebuild these packages (as these forks are mostly to track compatibility with current module dependencies for my own use and a few others), so I was surprised to see the PR! Thank you very much.

You have a nice service and I appreciate it being available for open-source project and recommend it to others.

**Comment by subham-deepsource** [comment]
> @subham-deepsource
> 
> I appreciate you looking into this - I don't always rebuild these packages (as these forks are mostly to track compatibility with current module dependencies for my own use and a few others), so I was surprised to see the PR! Thank you very much.
> 
> You have a nice service and I appreciate it being available for open-source project and recommend it to others.

Thank you so much @johnsonjh! Happy to help!

**Pull request merged**
